name: "Process new metadata entry"
on: 
  issues:
    types: [opened, edited]

jobs:
  process-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          pip install metomi-isodatetime
        
      - name: create metadata file
        id: create-file
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
          # pipe preseves newline properties for multilines
          ISSUE_SUBMITTER: ${{ github.event.issue.user.login }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python scripts/create_metadata_conf.py

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push