# (C) British Crown Copyright 2025, Met Office.
# Please see LICENSE.md for license details.

name: "Process new metadata entry"
on: 
  issues:
    types: [opened, edited]

jobs:
  process-metadata:
    if: contains(github.event.issue.labels.*.name, 'metadata_entry')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - uses: actions/checkout@v3
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: install dependencies
        run: |
          pip install metomi-isodatetime
        
      - name: create metadata file
        id: create-file
        env:
          ISSUE_BODY: |
              ${{ github.event.issue.body }}
          # pipe preseves newline properties for multilines
        run: python scripts/create_metadata_conf.py

      - name: return issues to user
        if: steps.create-file.outcome == 'failure'
        run: |
          gh issue comment "$NUMBER" --body "$BODY"
          echo "NOTE: Script failure has occured due to user input error. The user has been notified and instructed to 
          resubmit a corrected form. No further action required..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            Your metadata file contains incorrect or improperly formatted fields. 
            Please re submit you form and ammend the following issues:
            ${{ steps.create-file.outputs.warnings }}.

            If you believe this to be an error, please contact a member of the CDDS team.

            Thank you for your contribution.

      - name: check if file exists
        id: exists
        run: |
          if git ls-tree -r HEAD --name-only | grep -q "${{ steps.create-file.outputs.filename }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "exists=true"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "exists=false"
          fi

      - name: commit new file and close issue
        if: steps.exists.outputs.exists == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push origin main

          gh issue comment "$ISSUE" --body "$BODY"
          gh issue close --repo "$REPO" --comment "Closing issue $ISSUE" "$ISSUE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: >
            Your metadata file has been succesfully added to the repository as: 
            ${{ steps.create-file.outputs.filename }}

            Thank you for your contribution.
          
      - name: check diff
        id: diff
        if: steps.exists.outputs.exists == 'true'
        run: |
          if git diff --quiet HEAD -- ${{ steps.create-file.outputs.filename}}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: create PR 
        if: steps.diff.outputs.changed == 'true'
        run: | 
          branch="update-metadata-#${{ github.event.issue.number }}"
          git checkout -b "$branch"
          
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.cfg
          git commit -m "New workflow metadata file added from issue #${{ github.event.issue.number }}"
          git push origin "$branch"
          
          gh pr create \
            --title "Request to update existing metadata from issue #${{ github.event.issue.number }}" \
            --body "Request to update existing metadata configuration file from issue form:
                    -----------------------------------------------------
                    User: ${{ github.actor }} 
                    Issue title: ${{ github.event.issue.title }}
                    Issue ID: ${{ github.event.issue.number }}
                    Filename: ${{ steps.create-file.outputs.filename }}"  \
            --base main \
            --head $(git rev-parse --abbrev-ref HEAD)

          gh issue comment "$NUMBER" --body "$BODY"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: >
            A different version of this metadata file already exists, you can view the existing file here: 
            ${{ steps.create-file.outputs.filename }}.

            A pull request has been opened to review your changes. 

            Thank you for your contribution.
        
      - name: notify user of duplicate and close issue
        if: steps.diff.outputs.changed == 'false'
        run: |
          gh issue comment "$ISSUE" --body "$BODY"
          gh issue close --repo "$REPO" --comment "Closing issue $ISSUE" "$ISSUE"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.issue.number }}
          BODY: >
            This metadata file already exists, you can view the existing file here: 
            ${{ steps.create-file.outputs.filename }}.

            Thank you for your contribution.
