# (C) British Crown Copyright 2025, Met Office.
# Please see LICENSE.md for license details.

name: "Generate and deploy webview"
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 #full history

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: update html
        run: |
          python scripts/generate_metadata_tables.py

          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add *.html
          git commit -m "Metadata webview updated with new addition from issue template." || echo "No new changes to commit"
          git push origin main
